// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskItem = { name: string, diskSize: number, children: Array<DiskItem> | null, };