// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskItem = { id: string, name: string, children: Array<DiskItem> | null, size: number, };