// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskItemMetadata } from "./DiskItemMetadata";

export type DiskItem = { name: string, children: Array<DiskItem> | null, metadata: DiskItemMetadata, };