// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessDiskUsage } from "./ProcessDiskUsage";

export type Process = { name: string, cpuUsage: number, memoryUsage: number, cmd: Array<string>, exe: string, root: string, startTime: number, runTime: number, diskUsage: ProcessDiskUsage, status: string, };